### ISSUE TITLE
issue with installing 

### ISSUE THREAD

**Issue by Akshay-9416** [nicrusso7/rex-gym#23]
Hi, 
pip install rex_gym
is downloading all the versions of rex_gym and I see a lot of red in my terminal. 
please refer to the below image. Can someone tell me what's the issue and do I need to do anything else to install it in right
way. please let me know
Thank you 
![image](https://user-images.githubusercontent.com/60077708/120097379-c5329080-c14d-11eb-8002-a97d178d4fc2.png)

**Comment by nicrusso7** [comment]
Hello,
This looks like an issue with the rex-gym PyPi package and its dependencies, may I ask to install the lib from source?

Just clone this repository and run (from the project root folder):

`pip install .`

**Comment by Akshay-9416** [comment]
Hi, Thank you for your response
I tried,
pip install .
and this is the issue, refer below pic. 

![image](https://user-images.githubusercontent.com/60077708/120109741-64747980-c188-11eb-84fe-cc15afacb5be.png)

**Comment by nicrusso7** [comment]
Thanks for pointing this out, I’ll fix the dependencies tree ASAP. In the meanwhile you can just install it with:

`pip install --no-dependencies .`

**Comment by sffranke** [comment]
Hi, using Ubuntu 22.04.1 LTS the problem described above is still present. "pip install --no-dependencies ." Leads to a yoyo dance of pip's dependency resolver. Giving up at this early stage.

**Comment by zephirusgit** [comment]
Could I do it even if I don't have to do xD to see yourself in 3D? is training something ..
I leave my steps,
supply many versions until it worked


conda create -n spot python=3.7 anaconda
conda activate spot
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install rex_gym --no-dependencies .
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install cloudpickle==1.3.0
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install pyqt5==5.12
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install pyqtwebengine==5.12
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install cloudplicke==1.5.1
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install gym==0.17.1
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install pybullet==2.8.3
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install tensorflow==1.15.5
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install protobuf==3.20.0
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install numpy==1.18
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install daal==2021.4.0
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install cloudpickle==1.3.0
(spot) PS H:\ia\spotmicro\rex-gym-master> pip install tensorflow-probability==0.8
(spot) PS H:\ia\spotmicro\rex-gym-master> rex-gym train -e walk -log a.txt

**Comment by zephirusgit** [comment]
is alive! in 3d xD

 rex-gym train -e walk -log a.txt --playground True --env

**Comment by yuukix77** [comment]
the same

> Thanks for pointing this out, I’ll fix the dependencies tree ASAP. In the meanwhile you can just install it with:
> 
> `pip install --no-dependencies .`

I got it by using this way！Thanks

**Comment by ThapeloGithub** [comment]
i am getting this error: (rex) C:\Users\thapelo>rex-gym policy --env walk
Traceback (most recent call last):
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\thapelo\miniconda3\envs\rex\Scripts\rex-gym.exe\__main__.py", line 7, in <module>
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\rex_gym\cli\entry_point.py", line 27, in policy
    from rex_gym.playground.policy_player import PolicyPlayer
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\rex_gym\playground\policy_player.py", line 7, in <module>
    import tensorflow.compat.v1 as tf
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow\__init__.py", line 102, in <module>
    from tensorflow_core import *
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\thapelo\miniconda3\envs\rex\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
