### ISSUE TITLE
cannot run 

### ISSUE THREAD

**Issue by liamrhli** [nicrusso7/rex-gym#35]
The following errors are reported after installation and operation

(rex) lrh@lrh:~/桌面/rex-gym$ rex-gym policy -e walk
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorflow_core/python/framework/dtypes.py:597: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object,
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorflow_core/python/framework/dtypes.py:605: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool,
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py:106: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object:
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorflow_core/python/framework/tensor_util.py:108: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool:
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:568: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (np.object, string),
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:569: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (np.bool, bool),
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorboard/util/tensor_util.py:100: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object: SlowAppendObjectArrayToTensorProto,
/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/tensorboard/util/tensor_util.py:101: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: SlowAppendBoolArrayToTensorProto,
Traceback (most recent call last):
  File "/home/lrh/anaconda3/envs/rex/bin/rex-gym", line 8, in <module>
    sys.exit(cli())
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/rex_gym/cli/entry_point.py", line 31, in policy
    PolicyPlayer(env, args, signal_type).play()
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/rex_gym/playground/policy_player.py", line 29, in play
    config = utility.load_config(policy_dir)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/rex_gym/agents/scripts/utility.py", line 197, in load_config
    config = yaml.load(file_)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1071, in load
    return loader._constructor.get_single_data()
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 126, in construct_document
    data = self.construct_object(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 191, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 955, in construct_python_object_new
    return self.construct_python_object_apply(suffix, node, newobj=True)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 937, in construct_python_object_apply
    value = self.construct_mapping(node, deep=True)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 196, in construct_non_recursive_object
    for _dummy in generator:
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 674, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 191, in construct_non_recursive_object
    data = constructor(self, tag_suffix, node)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 865, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/ruamel/yaml/constructor.py", line 850, in find_python_name
    mark,
ruamel.yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'algorithm.PPOAlgorithm' in the module 'rex_gym.agents.ppo'
  in "/home/lrh/anaconda3/envs/rex/lib/python3.7/site-packages/rex_gym/policies/walk/ik/config.yaml", line 3, column 14

**Comment by kkavin43** [comment]
How did you solve this issue?

**Comment by liamrhli** [comment]
> In fact, I found that this is caused by incompatible software versions. When I execute pip install rex-gym,, I found that the version of 0.17 was installed instead of the latest version. When I installed through the cloned package, I found that the software libraries would conflict with each other and cancelled the version limit of gym in the  "requirements .txt" , that it can be installed smoothly, and rex-gym will be reinstalled to the latest version

**Comment by liamrhli** [comment]
> How did you solve this issue?

In fact, I found that this is caused by incompatible software versions. When I execute pip install rex-gym,, I found that the version of 0.17 was installed instead of the latest version. When I installed through the cloned package, I found that the software libraries would conflict with each other and cancelled the version limit of gym in the "requirements .txt" , that it can be installed smoothly, and rex-gym will be reinstalled to the latest version
